### PR TITLE
Add missing options: ifname, disassoc_low_ack, wpa_disable_eapol_key_…

### PR DESCRIPTION
**Pull request by eTimS**
…retries

### CODE REVIEW

**Comment by eTimS** [comment]
Hello!
Thanks for the nice collection, I'm configuring a router with it and noticed some missing options in the wifi configuration part.
I'm still using v0.1.1 for now (when using v0.1.4, it complained about the wireguard key folder not being present even if I had not enabled the wireguard role)
In summary, I tested theses changes with v0.1.1 but not with v0.1.4 yet!

**Comment by imp1sh** [comment]
Can you give me the error message from 0.1.4 when it complains about the wg path not being defined, please.

**Comment by eTimS** [comment]
Yes:
```
TASK [Gathering Facts] ******************************************************************************************************************************************************************************************************************************************************************************
[WARNING]: sftp transfer mechanism failed on [***]. Use ANSIBLE_DEBUG=1 to see detailed information
[WARNING]: Platform linux on host *** is using the discovered Python interpreter at /usr/bin/python3.9, but future installation of another Python interpreter could change the meaning of that path. See https://docs.ansible.com/ansible-
core/2.13/reference_appendices/interpreter_discovery.html for more information.
ok: [***]
TASK [imp1sh.ansible_openwrt.ansible_openwrtnetwork : make sure wireguard management dir exists] ****************************************************************************************************************************************************************************************************
fatal: [*** -> 127.0.0.1]: FAILED! => {"changed": false, "msg": "There was an issue creating /etc/wireguard as requested: [Errno 13] Permission denied: b'/etc/wireguard'", "path": "/etc/wireguard/ansiblekeys"}
```

After looking a bit at the "ansible_openwrtnetwork" role, I understand you had to add some wireguard config in this role too.
On my side, I have only using the roles ansible_openwrtnetwork and ansible_openwrtwireless (atm)

```
# main.yml
---
- hosts: router

  roles:
    - imp1sh.ansible_openwrt.ansible_openwrtnetwork
    - imp1sh.ansible_openwrt.ansible_openwrtwireless
```

**Comment by imp1sh** [comment]
Thx, it will be fixed in 0.1.5

**Pull request merged**
